# Generated by Django 5.2.4 on 2025-08-03 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(help_text='Mã cổ phiếu (VD: FPT, VCB)', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(help_text='Tên đầy đủ của công ty', max_length=255)),
                ('exchange', models.CharField(choices=[('HOSE', 'Sở Giao dịch Chứng khoán TP.HCM'), ('HNX', 'Sở Giao dịch Chứng khoán Hà Nội'), ('UPCOM', 'Thị trường Giao dịch Cổ phiếu Công ty Đại chúng chưa niêm yết'), ('OTHER', 'Khác')], default='HOSE', help_text='Sàn niêm yết', max_length=10)),
                ('industry', models.CharField(blank=True, help_text='Ngành nghề kinh doanh', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_email_alerts', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('PRICE_ABOVE', 'Giá vượt lên trên'), ('PRICE_BELOW', 'Giá giảm xuống dưới'), ('RSI_ABOVE', 'RSI vượt lên trên'), ('RSI_BELOW', 'RSI giảm xuống dưới'), ('MA_CROSS_ABOVE', 'Đường MA ngắn cắt lên đường MA dài'), ('VOLUME_SPIKE', 'Khối lượng tăng đột biến')], max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Cảnh báo có đang hoạt động không?')),
                ('triggered_at', models.DateTimeField(blank=True, help_text='Lần cuối cảnh báo được kích hoạt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
            ],
        ),
        migrations.CreateModel(
            name='PotentialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField(help_text='Thứ hạng tiềm năng')),
                ('score', models.FloatField(help_text='Điểm số kỹ thuật tổng hợp')),
                ('reason', models.TextField(help_text='Lý do/Tín hiệu được đề xuất (VD: MA20 cắt lên MA50, RSI < 30)')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
            ],
            options={
                'ordering': ['rank', 'analysis_date'],
                'unique_together': {('stock', 'analysis_date')},
            },
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Ngày giao dịch')),
                ('open', models.DecimalField(decimal_places=2, help_text='Giá mở cửa', max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, help_text='Giá cao nhất', max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, help_text='Giá thấp nhất', max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, help_text='Giá đóng cửa', max_digits=10)),
                ('volume', models.BigIntegerField(help_text='Khối lượng giao dịch')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='api.stock')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='api.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
