# Generated by Django 5.2.4 on 2025-08-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(help_text='Mã cổ phiếu (VD: FPT, VCB)', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
