# Generated by Django 5.2.4 on 2025-08-20 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_stock_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên nguồn tin (VD: VnExpress, CafeF)', max_length=100, unique=True)),
                ('base_url', models.URLField(help_text='URL trang chủ nguồn tin', max_length=255)),
                ('crawl_selector', models.CharField(blank=True, help_text='CSS selector để extract bài viết (nếu dùng Firecrawl với selectors)', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Nguồn tin tức',
                'verbose_name_plural': 'Nguồn tin tức',
            },
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': 'Cảnh báo', 'verbose_name_plural': 'Cảnh báo'},
        ),
        migrations.AlterModelOptions(
            name='potentialstock',
            options={'ordering': ['rank', 'analysis_date'], 'verbose_name': 'Cổ phiếu tiềm năng', 'verbose_name_plural': 'Cổ phiếu tiềm năng'},
        ),
        migrations.AlterModelOptions(
            name='stockdata',
            options={'ordering': ['-date'], 'verbose_name': 'Dữ liệu giá cổ phiếu', 'verbose_name_plural': 'Dữ liệu giá cổ phiếu'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name': 'Danh sách theo dõi', 'verbose_name_plural': 'Danh sách theo dõi'},
        ),
        migrations.AlterField(
            model_name='alert',
            name='condition_type',
            field=models.CharField(choices=[('PRICE_ABOVE', 'Giá vượt lên trên'), ('PRICE_BELOW', 'Giá giảm xuống dưới'), ('RSI_ABOVE', 'RSI vượt lên trên'), ('RSI_BELOW', 'RSI giảm xuống dưới'), ('MA_CROSS_ABOVE', 'MA ngắn cắt lên MA dài'), ('VOLUME_SPIKE', 'Khối lượng tăng đột biến')], help_text='Điều kiện cảnh báo', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo cảnh báo'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.stock'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='triggered_at',
            field=models.DateTimeField(blank=True, help_text='Lần cuối được kích hoạt', null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ngưỡng so sánh (VD: 100.5 cho giá, 70 cho RSI)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='potentialstock',
            name='analysis_date',
            field=models.DateField(help_text='Ngày phân tích'),
        ),
        migrations.AlterField(
            model_name='potentialstock',
            name='reason',
            field=models.TextField(help_text='Lý do/Tín hiệu được đề xuất'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='receive_email_alerts',
            field=models.BooleanField(default=True, help_text='Người dùng có nhận email cảnh báo không'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(choices=[('HOSE', 'Sở Giao dịch Chứng khoán TP.HCM'), ('HNX', 'Sở Giao dịch Chứng khoán Hà Nội'), ('UPCOM', 'Thị trường UPCOM'), ('OTHER', 'Khác')], default='HOSE', help_text='Sàn niêm yết', max_length=10),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề bài viết', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Mô tả ngắn/sapo', null=True)),
                ('content_markdown', models.TextField(help_text='Nội dung bài viết dạng Markdown (từ Firecrawl)')),
                ('url', models.URLField(help_text='URL gốc, dùng để tránh trùng lặp', max_length=500, unique=True)),
                ('published_at', models.DateTimeField(help_text='Ngày xuất bản')),
                ('crawled_at', models.DateTimeField(auto_now_add=True, help_text='Ngày hệ thống crawl bài viết')),
                ('author', models.CharField(blank=True, help_text='Tác giả bài viết', max_length=255, null=True)),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL ảnh thumbnail', max_length=500, null=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Bài viết đã được phân tích related_stocks chưa?')),
                ('related_stocks', models.ManyToManyField(blank=True, help_text='Các mã cổ phiếu được đề cập', related_name='articles', to='api.stock')),
                ('source', models.ForeignKey(help_text='Nguồn của bài viết', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.newssource')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-published_at'],
            },
        ),
    ]
