# Generated by Django 5.2.4 on 2025-09-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_newssource_alter_alert_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='potentialstock',
            options={'ordering': ['-confidence', '-score']},
        ),
        migrations.RemoveField(
            model_name='potentialstock',
            name='rank',
        ),
        migrations.AddField(
            model_name='potentialstock',
            name='confidence',
            field=models.PositiveIntegerField(default=0, help_text='Độ tự tin của gợi ý (0-100%)'),
        ),
        migrations.AddField(
            model_name='potentialstock',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Giá tại ngày phân tích', max_digits=10),
        ),
        migrations.AddField(
            model_name='potentialstock',
            name='key_reasons',
            field=models.TextField(blank=True, default='', help_text='Danh sách các lý do chính, cách nhau bởi dấu phẩy'),
        ),
        migrations.AddField(
            model_name='potentialstock',
            name='target_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Giá mục tiêu dự kiến', max_digits=10),
        ),
        migrations.AddField(
            model_name='potentialstock',
            name='timeframe',
            field=models.CharField(blank=True, default='', help_text='Khung thời gian gợi ý (Ngắn hạn, Trung hạn)', max_length=50),
        ),
        migrations.AlterField(
            model_name='potentialstock',
            name='analysis_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='potentialstock',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Mô tả chi tiết chiến lược'),
        ),
        migrations.AlterField(
            model_name='potentialstock',
            name='score',
            field=models.FloatField(default=0.0, help_text='Điểm số trên thang 10'),
        ),
    ]
