# Generated by Django 5.2.4 on 2025-09-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_stockdata_options_alter_stock_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialstock',
            name='stop_loss',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Giá stop loss dự kiến', max_digits=10),
        ),
    ]
