# Generated by Django 5.2.4 on 2026-02-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_potentialstock_key_reasons_chatsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
