# Generated by Django 5.2.4 on 2026-03-12 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_stock_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('state', models.CharField(choices=[('UPTREND', 'Uptrend'), ('DOWNTREND', 'Downtrend'), ('SIDEWAY', 'Sideway')], max_length=10)),
                ('confidence', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Market State',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('trend', 'Trend Prediction'), ('market_state', 'Market State'), ('anomaly', 'Anomaly Detection')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('features_used', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=dict)),
                ('trained_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ML Model',
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Mã có đang giao dịch không'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_type',
            field=models.CharField(blank=True, help_text='Loại CK từ SSI: S (cổ phiếu), ETF, CW, bond...', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='adj_close',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Giá đóng cửa đã điều chỉnh (closepriceadjusted từ SSI)', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField()),
                ('anomaly_type', models.CharField(max_length=50)),
                ('anomaly_score', models.FloatField()),
                ('details', models.JSONField(default=dict)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='api.stock')),
            ],
            options={
                'verbose_name': 'Anomaly Alert',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('trend_class', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('SIDEWAY', 'Sideway')], max_length=10)),
                ('trend_probability', models.JSONField(default=dict, help_text='{up: 0.72, down: 0.10, sideway: 0.18}')),
                ('target_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stop_loss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('confidence_score', models.PositiveIntegerField(default=0)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mlmodel')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='api.stock')),
            ],
            options={
                'verbose_name': 'ML Prediction',
                'ordering': ['-confidence_score'],
                'unique_together': {('stock', 'prediction_date')},
            },
        ),
    ]
