# Generated by Django 5.2.4 on 2026-04-10 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_marketstate_mlmodel_stock_is_active_stock_stock_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLStock',
            fields=[
                ('ticker', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange', models.CharField(blank=True, max_length=10, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ML Stock',
            },
        ),
        migrations.AlterField(
            model_name='anomalyalert',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='api.mlstock'),
        ),
        migrations.AlterField(
            model_name='mlprediction',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='api.mlstock'),
        ),
        migrations.CreateModel(
            name='MLStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('adj_close', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_data_points', to='api.mlstock')),
            ],
            options={
                'verbose_name': 'ML Stock Data',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', 'date'], name='api_mlstock_stock_i_e3d18c_idx'), models.Index(fields=['date'], name='api_mlstock_date_c2b2bd_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
